--- 
apiVersion: v1
kind: Pod
metadata:
  name: test-1

spec:
  containers:
    - name: httpd
      image: httpd
      ports: 
        - containerPort: 80
      resources: 
        requests:
          cpu: 500m
          memory: 250Mi
        limits:
          cpu: 250m
          memory: 100Mi