--- 
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels: 
    app: alpine-q
spec: 
  - initContainers:
     - name: alpine
       image: alpine
       args: 
         - sleep
         - 10s
    containers:
      name: nginx-1
      image: nginx
      ports:
        containerPort: 80
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 250m
          memory: 250Mi
