--- 
apiVersion: v1
kind: Pod
metadata:
  name: test-1
  labels:
    app: alpine
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: init
      image: alpine
      args: 
        - sleep
        - 10s
  containers:
    - name: nginx-1
      image: ininx
      resources:
        limits:
          cpu: 500m
          memory: 250Mi
        requests:
          cpu: 250m 
          memory: 150Mi

