--- 
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: spc-deploy
  labels: 
    app: spring
spec:
  minReadySeconds: 15
  replicas: 4
  selector: 
    matchLabels: 
      app: spring-pet
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      labels: 
        app: spring-pet
    spec:
      containers:
        - name: pod-spc
          image: jenkins/jenkins:lts-jdk17
          ports: 
            - containerPort: 8080
          