--- 
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
  labels:
    app: spc-svc
spec:
  type: NodePort
  selector: 
    app: spring-pet
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30500