--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: spc-rs
  labels:
    app: spring
spec:
  replicas: 4
  minReadySeconds: 15
  selector: 
    matchLabels:
      app: spc-pet
  template:
    metadata:
      labels:
        app: spc-pet
    spec:
      containers:
        - name: spc-con
          image: dhillevajja/spc-march:43
          ports:
            - containerPort: 8080
      
--- 
apiVersion: v1
kind: Service 
metadata: 
  name: spc-svc
  labels: 
    app: sercice-spc
spec:
  type: NodePort
  selector:
    app: spc-pet
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  
          
