--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-1
  labels:
    app: mgnix
    version: v1.0
spec:
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - name: nginx-c
          image: httpd
          ports:
            - containerPort: 80
          resources: 
            limits:
              cpu: 1000m
              memory: 500Mi
            requests: 
              cpu: 150m 
              memory: 100Mi


--- 
apiVersion: v1
kind: Service
metadata:
  name: ng-svc
  labels: 
    app: svc
spec: 
  type: NodePort
  selector: 
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31500
             

